# config/deploy.yml
service: server
image: ashleyrudland87/ash
servers:
    - 195.201.25.22
registry:
    username:
        - KAMAL_REGISTRY_USERNAME
    password:
        - KAMAL_REGISTRY_PASSWORD
port: 3000
volumes:
  - "data:/data"